[mypy]
packages = elementary
exclude = ^elementary/monitor/dbt_project/
check_untyped_defs = true

# dbt-core is an optional dependency (only installed via the dbt1-* extras)
[mypy-dbt,dbt.*]
ignore_missing_imports = True

[mypy-alive_progress]
ignore_missing_imports = True

[mypy-ruamel]
ignore_missing_imports = True

[mypy-posthog]
ignore_missing_imports = True

[mypy-networkx]
ignore_missing_imports = True
