name: Bump version
on:
  workflow_dispatch:
    inputs:
      cli-version:
        type: string
        required: true
        description: New cli version
      dbt-package-version:
        type: string
        required: false
        description: Elementary package version (will use cli version if not provided)

  workflow_call:
    inputs:
      cli-version:
        type: string
        required: true
      dbt-package-version:
        type: string
        required: false

permissions: {}

jobs:
  validate-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      validated-cli-version: ${{ steps.validate-cli-input.outputs.cli-validation }}
      default-dbt-package-version: ${{ steps.validate-cli-input.outputs.cli-validation }}
      validated-dbt-package-version: ${{ steps.validate-dbt-package-input.outputs.dbt-package-validation }}
    steps:
      - name: validate cli version input
        id: validate-cli-input
        env:
          CLI_VERSION: ${{ inputs.cli-version }}
        run: |
          if [[ "$CLI_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "cli-validation=$CLI_VERSION" >> "$GITHUB_OUTPUT"
          fi
      - name: validate dbt package version
        if: ${{ inputs.dbt-package-version }}
        id: validate-dbt-package-input
        env:
          DBT_PACKAGE_VERSION: ${{ inputs.dbt-package-version }}
        run: |
          if [[ "$DBT_PACKAGE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "dbt-package-validation=$DBT_PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
          fi
      - name: echo versions
        env:
          CLI_VERSION: ${{ steps.validate-cli-input.outputs.cli-validation }}
          DBT_PACKAGE_VERSION: ${{ steps.validate-dbt-package-input.outputs.dbt-package-validation }}
        run: |
          echo "cli version: $CLI_VERSION"
          echo "dbt package version: $DBT_PACKAGE_VERSION"
      - name: fail on invalid input
        if: ${{ steps.validate-cli-input.outputs.cli-validation == '' || (inputs.dbt-package-version != '' && steps.validate-dbt-package-input.outputs.dbt-package-validation == '') }}
        uses: actions/github-script@v8
        with:
          script: |
            core.setFailed("Invalid version inputs")

  bump-version:
    needs: validate-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      CLI_VERSION: ${{ needs.validate-version.outputs.validated-cli-version }}
      DBT_PACKAGE_VERSION: ${{ needs.validate-version.outputs.validated-dbt-package-version || needs.validate-version.outputs.default-dbt-package-version }}
      RELEASE_BRANCH: release/v${{ needs.validate-version.outputs.validated-cli-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      # dbt-core==1.8 is the first dbt version we support
      - name: Install dbt-core
        run: pip install "dbt-core==1.8"
      - name: Create release branch
        run: git checkout -b "$RELEASE_BRANCH"
      - name: Initial config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Bump version
        run: |
          sed -i "s/^version = \"[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\"/version = \"$CLI_VERSION\"/" ./pyproject.toml
      - name: Bump dbt package version
        run: |
          sed -i "s/version: [0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$/version: $DBT_PACKAGE_VERSION/" ./elementary/monitor/dbt_project/packages.yml
          dbt deps --lock --project-dir elementary/monitor/dbt_project
      - name: Commit changes
        run: git commit -am "release v$CLI_VERSION"
      - name: Push code
        run: git push origin "$RELEASE_BRANCH"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.RELEASE_BRANCH }}
          base: master
          title: "Release v${{ env.CLI_VERSION }}"
          body: "Opened automatically using bump version workflow"

  update-docs-branch:
    needs: validate-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      DBT_PACKAGE_VERSION: ${{ needs.validate-version.outputs.validated-dbt-package-version || needs.validate-version.outputs.default-dbt-package-version }}
      DOCS_RELEASE_BRANCH: release/docs-v${{ needs.validate-version.outputs.validated-cli-version }}
    steps:
      - name: Checkout docs branch
        uses: actions/checkout@v6
        with:
          ref: docs
      - name: Create docs release branch
        run: git checkout -b "$DOCS_RELEASE_BRANCH"
      - name: Initial config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Bump dbt package
        run: |
          files=(
            docs/snippets/quickstart-package-install.mdx
            docs/data-tests/dbt/upgrade-package.mdx
          )
          for file in "${files[@]}"; do
            sed -i "s/version: [0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$/version: $DBT_PACKAGE_VERSION/" "./$file"
          done
      - name: Commit changes
        run: |
          git commit -am "docs: bump package version to v$DBT_PACKAGE_VERSION"
      - name: Push code
        run: git push origin "$DOCS_RELEASE_BRANCH"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.DOCS_RELEASE_BRANCH }}
          base: docs
          title: "Docs: bump dbt package to v${{ env.DBT_PACKAGE_VERSION }}"
          body: "Opened automatically using bump version workflow"
