name: Close Pylon Ticket on Issue or Pull Request Closure

on:
  issues:
    types: [closed]
  pull_request_target:
    types: [closed]

permissions: {}

jobs:
  close_pylon_ticket:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Extract Pylon Ticket ID
        id: extract_ticket_id
        env:
          EVENT_BODY: ${{ github.event_name == 'issues' && github.event.issue.body || github.event.pull_request.body }}
        run: |
          pylon_ticket_id=$(echo "$EVENT_BODY" | grep -oP '(?<=<!-- pylon-ticket-id: )\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b(?= -->)')
          echo "pylon_ticket_id=$pylon_ticket_id" >> "$GITHUB_OUTPUT"

      - name: Close Pylon Ticket
        if: steps.extract_ticket_id.outputs.pylon_ticket_id != ''
        run: |
          pylon_ticket_id=${{ steps.extract_ticket_id.outputs.pylon_ticket_id }}
          echo "Closing Pylon Ticket ID: $pylon_ticket_id"
          curl --request PATCH \
            --url "https://api.usepylon.com/issues/$pylon_ticket_id" \
            --header "Authorization: ${{ secrets.PYLON_API_KEY }}" \
            --header 'Content-Type: application/json' \
            --data '{
              "state": "closed"
            }'
