name: Dependency Review
on: [pull_request, workflow_dispatch]

permissions: {}

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
