name: Notify Slack
on:
  workflow_call:
    inputs:
      result:
        type: string
        required: true
      run_id:
        type: string
        required: false
      workflow_name:
        type: string
        required: true

permissions: {}

jobs:
  print_inputs:
    timeout-minutes: 2
    name: print inputs
    runs-on: ubuntu-latest
    steps:
      - name: print
        env:
          RUN_ID: ${{ inputs.run_id }}
          WORKFLOW_NAME: ${{ inputs.workflow_name }}
          RESULT: ${{ inputs.result }}
        run: |
          echo "$RUN_ID"
          echo "$WORKFLOW_NAME"
          echo "$RESULT"

  notify:
    name: Notify Slack Failure
    timeout-minutes: 3
    runs-on: ubuntu-latest
    if: ${{ inputs.result == 'failure' }}
    steps:
      - name: Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          WORKFLOW_NAME: ${{ inputs.workflow_name }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ inputs.run_id }}
        run: |
          payload="$(
            jq -n \
              --arg text "Scheduled Run Failed - $WORKFLOW_NAME" \
              --arg run_url "$RUN_URL" \
              '{
                text: $text,
                attachments: [
                  {
                    color: "danger",
                    fields: [
                      {
                        title: "URL:",
                        value: $run_url
                      }
                    ]
                  }
                ]
              }'
          )"

          curl --fail --show-error --silent \
            --header "Content-Type: application/json" \
            --data "$payload" \
            "$SLACK_WEBHOOK_URL"
