name: Notify Slack
on:
  workflow_call:
    inputs:
      result:
        type: string
        required: true
      run_id:
        type: string
        required: false
      workflow_name:
        type: string
        required: true

jobs:
  notify:
    name: Notify Slack Failure
    runs-on: ubuntu-latest
    if: ${{ inputs.result == 'failure' }}
    steps:
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.DEPLOY_SLACK_WEBHOOK_URL }}
        with:
          text: Scheduled Run Failed - ${{ inputs.workflow_name }}
          attachments: |
            [
                {
                "color": "danger",
                "fields": 
                [
                    {
                    "title": "URL:",
                    "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ inputs.run_id }}"
                    }
                ]
                }
            ]
