name: Test main warehouse platform
on:
  push:
    branches: ["master"]
    paths:
      - elementary/**
      - setup.py
  pull_request:
    branches: ["master"]
    paths:
      - elementary/**
      - setup.py
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: postgres
      dbt-version: 1.0.2
    secrets: inherit
