name: Test main warehouse platform
on:
  pull_request_target:
    branches: ["master"]
    paths:
      - elementary/**
      - .github/**
      - pyproject.toml
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-warehouse.yml
    with:
      warehouse-type: postgres
      elementary-ref: ${{ (github.event_name == 'pull_request_target' && github.event.pull_request.head.sha) || '' }}
    secrets: inherit
