name: Unit tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.8", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python modules
        run: |
          pip install --no-cache -r "dev-requirements.txt"
          pip install --no-cache -r "requirements.txt"
      - name: Run pytest
        run: |
          pytest -s tests
